# Generated by Django 3.1.2 on 2024-01-31 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20240130_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentPosition',
        ),
    ]
